<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'thephpcc\\cqrs\\departureboard\\departureinformationboard' => '/DepartureInformationBoard.php',
                'thephpcc\\cqrs\\departureboard\\flight' => '/Flight.php',
                'thephpcc\\cqrs\\departureboard\\projector' => '/Projector.php',
                'thephpcc\\cqrs\\event' => '/Event.php',
                'thephpcc\\cqrs\\eventstore' => '/EventStore.php',
                'thephpcc\\cqrs\\eventstorestub' => '/EventStoreStub.php',
                'thephpcc\\cqrs\\flightcancelledevent' => '/FlightCancelledEvent.php',
                'thephpcc\\cqrs\\flightscheduledevent' => '/FlightScheduledEvent.php',
                'thephpcc\\cqrs\\helloworld' => '/HelloWorld.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
